version: '3.1'

services:
    monolith:
        build: docker/dev/php
        working_dir: /var/www/project
        volumes:
            - ./monolith:/var/www/project:delegated
    laravel:
        build: docker/dev/php
        working_dir: /var/www/project
        volumes:
            - ./laravel-microservice:/var/www/project:delegated
        links:
          - db

    nginx:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "9898:80"
        volumes:
            - ./laravel-microservice:/var/www/project:delegated
            - ./docker/dev/nginx/app.conf:/etc/nginx/conf.d/default.conf
        links:
          - laravel

    db:
        image: mysql:5.7.22
        restart: unless-stopped
        ports:
            - "3310:3306"
        environment:
            MYSQL_DATABASE: admin
            MYSQL_ROOT_PASSWORD: admin
