services:
    account.api.implementation:
        arguments:
            - '@App\Module\Account\API\GoMonolithClient'
        class: App\Module\Account\API\GoAccountAPI

    App\UI\CLI\AccountCommand:
        class: App\UI\CLI\AccountCommand
        arguments:
            - '@App\UI\CLI\Actions\ActionsManager'
            - '@account.api.implementation'
        tags:
            - { name: 'console' }

    App\Module\Shared\Infrastructure\EventStore\EventStore:
        class: App\Module\Shared\Infrastructure\EventStore\EventStore

    App\Module\Account\Main\Infrastructure\Repository\AccountRepository:
        arguments:
            - '@App\Module\Shared\Infrastructure\EventStore\EventStore'
        class: App\Module\Account\Main\Infrastructure\Repository\AccountRepository

    App\Module\Account\Main\Application\AccountService:
        class: App\Module\Account\Main\Application\AccountService
        arguments:
            - '@App\Module\Account\Main\Infrastructure\Repository\AccountRepository'
        public: true

    App\Module\Account\API\LaravelMonolithClient:
        class: App\Module\Account\API\LaravelMonolithClient

    App\Module\Account\API\GoMonolithClient:
        class: App\Module\Account\API\GoMonolithClient

    App\UI\CLI\Actions\ActionsManager:
        class: App\UI\CLI\Actions\ActionsManager

    App\UI\CLI\Actions\Specification\AddAccountAction:
        class: App\UI\CLI\Actions\Specification\AddAccountAction
        arguments:
            - '@account.api.implementation'
        tags:
            - {name: 'action'}

    App\UI\CLI\Actions\Specification\AddBalanceAction:
        class: App\UI\CLI\Actions\Specification\AddBalanceAction
        arguments:
            - '@account.api.implementation'
        tags:
            - {name: 'action'}

    App\UI\CLI\Actions\Specification\GetSingleAction:
        class: App\UI\CLI\Actions\Specification\GetSingleAction
        arguments:
            - '@account.api.implementation'
        tags:
            - {name: 'action'}

    App\UI\CLI\Actions\Specification\WithdrawAction:
        class: App\UI\CLI\Actions\Specification\WithdrawAction
        arguments:
            - '@account.api.implementation'
        tags:
            - {name: 'action'}