services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\UI\CLI\AccountCommand:
        class: App\UI\CLI\AccountCommand
        arguments:
            - '@App\Module\Account\API\ImplAccountAPI'
        tags:
            - { name: 'console' }

    App\Module\Account\API\ImplAccountAPI:
        arguments:
            - '@App\Module\Account\Main\Application\AccountService'
        class: App\Module\Account\API\ImplAccountAPI

    App\Module\Account\Main\Application\AccountService:
        class: App\Module\Account\Main\Application\AccountService
        public: true